#!/bin/sh

export status_file=/root/status
echo "Start init" > $status_file

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

initramfsboot=0
for i in "$@"; do
    case $i in
    initramfsboot)
        initramfsboot=1
        ;;
    esac
done

if [[ $initramfsboot -eq 1 ]]; then
    exec /sbin/init "$@"
fi

export PATH=/sbin:/usr/sbin:/bin:/usr/bin
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run
mkdir -m 0755 /run/initramfs

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir -m 0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc

bin/hostname -F /etc/hostname
mknod /dev/sev c 10 127

# Execute init.d scripts directly in sorted order.
for i in /etc/init.d/S??* ;do
     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done

overlay_destination=/mnt/sda
if [ "`ls -A $overlay_destination`" != "" ]; then
    mount -n -o move /run $overlay_destination/run
    mount -n -o move /proc $overlay_destination/proc
    mount -n -o move /sys $overlay_destination/sys
    mount -n -o move /dev $overlay_destination/dev
    exec run-init $overlay_destination /sbin/init "$@"
fi
